version: "3.9"
services:
  web:
    image: ibrarullah/goapp:${{ steps.get_commit_sha.outputs.commit_sha }}
    ports:
      - 4040:4040
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
