version: "3.9"
services:
  web:
    build: .
    ports:
      - 4040:4040
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306