name: Push Docker image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the latest Git tag
        id: get_latest_tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"

      - name: Remove leading 'v' from tag
        id: remove_v
        run: echo "::set-output name=tag::${{ steps.get_latest_tag.outputs.tag }}"

      - name: Increment tag
        id: increment_tag
        run: echo "::set-output name=tag::$((${{ steps.remove_v.outputs.tag }} + 1))"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ibrarullah/goapp:latest
            ibrarullah/goapp:${{ steps.increment_tag.outputs.tag }}

          labels: |
            maintainer=ibrarullah204@gmail.com
            description=Go todo app pushed by GitHub Actions
            version=${{ steps.increment_tag.outputs.tag }}
